//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Account1 = new HashSet<Account>();
            this.Activity = new HashSet<Activity>();
            this.Contact1 = new HashSet<Contact>();
            this.AccountCommunication = new HashSet<AccountCommunication>();
            this.ContactCareer = new HashSet<ContactCareer>();
            this.AccountAddress = new HashSet<AccountAddress>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedById { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> OwnershipId { get; set; }
        public Nullable<System.Guid> PrimaryContactId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> OwnerId { get; set; }
        public Nullable<System.Guid> IndustryId { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
        public string Phone { get; set; }
        public string AdditionalPhone { get; set; }
        public string Fax { get; set; }
        public string Web { get; set; }
        public Nullable<System.Guid> AddressTypeId { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> RegionId { get; set; }
        public string Zip { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> AccountCategoryId { get; set; }
        public Nullable<System.Guid> EmployeesNumberId { get; set; }
        public Nullable<System.Guid> AnnualRevenueId { get; set; }
        public string Notes { get; set; }
        public byte[] Logo { get; set; }
        public string AlternativeName { get; set; }
        public int ProcessListeners { get; set; }
        public string GPSN { get; set; }
        public string GPSE { get; set; }
        public Nullable<System.Guid> PriceListId { get; set; }
        public int Completeness { get; set; }
        public Nullable<System.Guid> AccountLogoId { get; set; }
        public Nullable<System.Guid> UsrAuthorId { get; set; }
        public int UsrB7Count { get; set; }
        public int UsrScaniaCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual Contact Contact2 { get; set; }
        public virtual AccountIndustry AccountIndustry { get; set; }
        public virtual Contact Contact3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountCommunication> AccountCommunication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactCareer> ContactCareer { get; set; }
        public virtual Country Country { get; set; }
        public virtual City City { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountAddress> AccountAddress { get; set; }
    }
}
