//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAddress
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedById { get; set; }
        public Nullable<System.Guid> AddressTypeId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> RegionId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public bool Primary { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public int ProcessListeners { get; set; }
        public string GPSN { get; set; }
        public string GPSE { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual City City { get; set; }
        public virtual Region Region { get; set; }
        public virtual Country Country { get; set; }
    }
}
