//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtBPMEntities : DbContext
    {
        public AtBPMEntities()
            : base("name=AtBPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<ContactCommunication> ContactCommunication { get; set; }
        public virtual DbSet<AccountIndustry> AccountIndustry { get; set; }
        public virtual DbSet<AccountCommunication> AccountCommunication { get; set; }
        public virtual DbSet<ContactCareer> ContactCareer { get; set; }
    }
}
