//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactCommunication
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedById { get; set; }
        public Nullable<System.Guid> CommunicationTypeId { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public int Position { get; set; }
        public string SocialMediaId { get; set; }
        public string SearchNumber { get; set; }
        public int ProcessListeners { get; set; }
        public string Number { get; set; }
        public bool IsCreatedBySynchronization { get; set; }
        public bool NonActual { get; set; }
        public Nullable<System.Guid> NonActualReasonId { get; set; }
        public Nullable<System.DateTime> DateSetNonActual { get; set; }
        public string ExternalCommunicationType { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
