//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactCareer
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedById { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public string JobTitle { get; set; }
        public bool Primary { get; set; }
        public bool Current { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.Guid> JobChangeReasonId { get; set; }
        public string Description { get; set; }
        public int ProcessListeners { get; set; }
        public Nullable<System.Guid> DecisionRoleId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Job Job { get; set; }
    }
}
