//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Task
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.Guid> PriorityID { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public Nullable<System.Guid> OpportunityID { get; set; }
        public Nullable<System.Guid> InvoiceID { get; set; }
        public Nullable<System.Guid> StatusID { get; set; }
        public Nullable<System.Guid> TypeID { get; set; }
        public Nullable<int> PercentDue { get; set; }
        public Nullable<System.Guid> ResultID { get; set; }
        public string DetailedResult { get; set; }
        public Nullable<int> ShowInScheduler { get; set; }
        public byte[] Description { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> ActualFinishDate { get; set; }
        public Nullable<int> ActualDurationHours { get; set; }
        public Nullable<int> ActualDurationMinutes { get; set; }
        public Nullable<System.Guid> RemindingToAuthorID { get; set; }
        public Nullable<System.Guid> RemindingToOwnerID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<int> ActualDuration { get; set; }
        public Nullable<System.Guid> CycleTaskParamID { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Contact tbl_Contact { get; set; }
        public virtual tbl_Contact tbl_Contact1 { get; set; }
        public virtual tbl_TaskResult tbl_TaskResult { get; set; }
    }
}
