//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountAddress
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByID { get; set; }
        public Nullable<System.Guid> AddressTypeID { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public Nullable<System.Guid> StateID { get; set; }
        public string ZIP { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public Nullable<int> IsPrimary { get; set; }
        public Nullable<System.Guid> TerritoryID { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        public virtual tbl_State tbl_State { get; set; }
    }
}
