//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactCareer
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public Nullable<System.Guid> MotiveID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<int> IsPrimary { get; set; }
        public Nullable<int> IsCurrent { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Contact tbl_Contact { get; set; }
        public virtual tbl_Job tbl_Job { get; set; }
    }
}
